- name: Install & Run Clickhouse
  hosts: clickhouse
  become: True
  tasks:
    - name: Include app variables
      include_vars: vars.yml

    - name: Rename Machine
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: '^{{ server_default_name }}'
        line: 'wav3-clickhouse-single'

    - name: Reboot machine to populate name change
      ansible.builtin.reboot:

    - name: Add CH apt Key
      apt_key:
        url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
        state: present

    - name: Add CH Repository
      apt_repository:
        repo: deb https://packages.clickhouse.com/deb lts main
        state: present

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes 

    - name: Install Clickhouse server
      package:
          name: clickhouse-server
          state: present

    - name: Install Clickhouse client
      package:
          name: clickhouse-client
          state: present


    - name: Copy modified config file
      ansible.builtin.copy:
          src: /Users/main_account/Documents/Projects/wav3_/configs/server_configs/ch_config.xml
          dest: /etc/clickhouse-server/config.xml

    - name: Start Clickhouse service
      ansible.builtin.service:
          name: clickhouse-server
          state: started 
