- name: Install & Run Clickhouse
  hosts: clickhouse
  become: True
  tasks:
    - name: Install Clickhouse server
      package:
          name: clickhouse-server
          state: present

    - name: Install Clickhouse client
      package:
          name: clickhouse-client
          state: present

    - name: Start Clickhouse service
      ansible.builtin.service:
          name: clickhouse-server
          state: started 
