- name: Install Docker and run daemon
  hosts: kafka, redis
  become: True
  tasks:
    - name: Include app variables
      include_vars: vars.yml

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    
    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start Docker daemon
      service:
        name: docker
        state: started
        enabled: yes
