- name: Get Kafka Docker Image and Start
  hosts: kafka
  become: True
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: apache/kafka:3.9.0
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: kafka_broker
        image: apache/kafka
        state: started
        ports:
          - 29093:29093
        env:
          KAFKA_NODE_ID: "1"
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,EXTERNAL_DIFFERENT_HOST://:29093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL_DIFFERENT_HOST://{{ kafka_broker_ip_addr  }}:29093
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
          KAFKA_NUM_PARTITIONS: "1"

