- name: Get Redis Docker Image and Start
  hosts: redis
  become: True
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: redis/redis-stack:latest
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: redis_server
        image: redis/redis-stack
        state: started
        ports:
          - 6379:6379
          - 8001:8001
